Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you might choose one over the other.


Ordinal Encoding assigns integers to categorical variables based on order or rank. Label Encoding also assigns integers to categories, but it does not consider any particular order among them. 

Use Ordinal Encoding when the categories have a natural order (e.g., low, medium, high). Use Label Encoding when the categories are nominal (e.g., red, blue, green), and no order exists.


Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in a machine learning project.


Target Guided Ordinal Encoding assigns numerical values to categorical levels based on the mean of the target variable for each category. 

For example, if you're predicting income based on job title, and average incomes are: Manager - 70k, Clerk - 40k, Executive - 90k, you would encode Executive: 3, Manager: 2, Clerk: 1.


Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated?


Covariance is a measure of the relationship between two variables, indicating the direction of their linear relationship. If the covariance is positive, the variables tend to increase together; if negative, one tends to decrease when the other increases.

Covariance between variables X and Y is calculated as:

\ [
\text{Cov}(X, Y) = \frac{1}{n - 1} \sum_{i=1}^n (X_i - \bar{X})(Y_i - \bar{Y})
\ ]


Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium, large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library. Show your code and explain the output.


In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
data = pd.DataFrame({
    'Color': ['red', 'green', 'blue'],
    'Size': ['small', 'medium', 'large'],
    'Material': ['wood', 'metal', 'plastic']
})
label_encoders = {}
for column in data.columns:
    le = LabelEncoder()
    data[column] = le.fit_transform(data[column])
    label_encoders[column] = le
print(data)

   Color  Size  Material
0      2     2         2
1      1     1         0
2      0     0         1


Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education level. Interpret the results.


In [2]:
import pandas as pd
import numpy as np
data = pd.DataFrame({
    'Age': [25, 32, 47, 51, 62],
    'Income': [50000, 60000, 75000, 82000, 90000],
    'Education': [12, 16, 16, 18, 20]
})
cov_matrix = np.cov(data.T)
print(cov_matrix)

[[2.213e+02 2.408e+05 4.080e+01]
 [2.408e+05 2.648e+08 4.530e+04]
 [4.080e+01 4.530e+04 8.800e+00]]


Q6. You are working on a machine learning project with a dataset containing several categorical variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD), and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for each variable, and why?


For "Gender", use Label Encoding since it's binary. 

For "Education Level", use Ordinal Encoding because it has a natural order.

For "Employment Status", use One-Hot Encoding if there's no ordinal relationship, or Target Guided Ordinal Encoding if there is a relationship with the target variable.


Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/ East/West). Calculate the covariance between each pair of variables and interpret the results.


In [3]:
import pandas as pd
import numpy as np
data = pd.DataFrame({
    'Temperature': [20, 22, 23, 19, 25],
    'Humidity': [30, 45, 50, 40, 60],
    'Weather Condition': ['Sunny', 'Cloudy', 'Rainy', 'Sunny', 'Rainy'],
    'Wind Direction': ['North', 'South', 'East', 'West', 'North']
})
data_encoded = data.copy()
data_encoded['Weather Condition'] = data_encoded['Weather Condition'].astype('category').cat.codes
data_encoded['Wind Direction'] = data_encoded['Wind Direction'].astype('category').cat.codes
cov_matrix = data_encoded.cov()
print(cov_matrix)

                   Temperature  Humidity  Weather Condition  Wind Direction
Temperature               5.70     23.75              -1.20           -1.65
Humidity                 23.75    125.00              -5.00           -3.75
Weather Condition        -1.20     -5.00               0.70            0.15
Wind Direction           -1.65     -3.75               0.15            1.30
