Q1. What is Min-Max scaling, and how is it used in data preprocessing? Provide an example to illustrate its application.


Min-Max scaling is a normalization technique used in data preprocessing to scale the values of numerical features to a specific range, typically [0, 1] or [-1, 1]. It is calculated using the formula:

X_scaled =(X - X_min)/(X_max - X_min) * (new_max - new_min) + new_min

This technique helps to bring all features to a common scale, which improves the performance of many machine learning algorithms like KNN or gradient descent-based models.


In [1]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
data = np.array([[10], [20], [30], [40], [50]])
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(data)
print(scaled_data)

[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


Q2. What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling? Provide an example to illustrate its application.


The Unit Vector technique (also called normalization) scales each sample (row) to have a unit norm, typically a length of 1. It is useful when the direction of the data matters more than its magnitude, such as in text classification with TF-IDF.

In contrast, Min-Max scaling operates column-wise and preserves the shape of the feature distribution.

Unit vector normalization:
X_normalized = X||X||


In [2]:
from sklearn.preprocessing import Normalizer
import numpy as np
data = np.array([[1, 2, 3], [4, 5, 6]])
scaler = Normalizer()
normalized_data = scaler.fit_transform(data)
print(normalized_data)

[[0.26726124 0.53452248 0.80178373]
 [0.45584231 0.56980288 0.68376346]]


Q3. What is PCA (Principle Component Analysis), and how is it used in dimensionality reduction? Provide an example to illustrate its application.


Principal Component Analysis (PCA) is a technique for reducing the dimensionality of datasets by transforming the data into a new set of orthogonal axes (principal components), ordered by the amount of variance they explain. It helps to simplify data while retaining important patterns.

PCA is used when datasets have many interdependent variables and aims to capture the most information with fewer dimensions.


In [3]:
from sklearn.decomposition import PCA
import numpy as np
data = np.array([[2.5, 2.4], [0.5, 0.7], [2.2, 2.9]])
pca = PCA(n_components=1)
transformed = pca.fit_transform(data)
print(transformed)

[[-0.81517689]
 [ 1.79187826]
 [-0.97670137]]


Q4. What is the relationship between PCA and Feature Extraction, and how can PCA be used for Feature Extraction? Provide an example to illustrate this concept.


PCA is a form of feature extraction because it transforms the original features into a new set of features (principal components). These components are combinations of the original variables, which can represent the data more efficiently.

By selecting the top-k components that explain most of the variance, PCA reduces dimensionality while retaining essential information.

Example: Reducing 10 correlated features to 3 principal components that explain 95% of the data's variance.


Q5. You are working on a project to build a recommendation system for a food delivery service. The dataset contains features such as price, rating, and delivery time. Explain how you would use Min-Max scaling to preprocess the data.


To preprocess the food delivery dataset, Min-Max scaling can be applied to features like price, rating, and delivery time to bring them to a common scale.

This helps the model treat all features equally without being biased by features on a larger numerical scale.

Each feature is scaled between 0 and 1 using Min-Max scaling before feeding the data into the recommendation model.


Q6. You are working on a project to build a model to predict stock prices. The dataset contains many features, such as company financial data and market trends. Explain how you would use PCA to reduce the dimensionality of the dataset.


PCA can be used on the stock prediction dataset by first standardizing the features and then applying PCA to reduce high-dimensional financial and market indicators to a smaller number of uncorrelated principal components.

This improves model efficiency, reduces noise, and helps in visualizing important patterns in the dataset.


Q7. For a dataset containing the following values: [1, 5, 10, 15, 20], perform Min-Max scaling to transform the values to a range of -1 to 1.


In [4]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
data = np.array([1, 5, 10, 15, 20]).reshape(-1, 1)
scaler = MinMaxScaler(feature_range=(-1, 1))
scaled_data = scaler.fit_transform(data)
print(scaled_data.flatten())

[-1.         -0.57894737 -0.05263158  0.47368421  1.        ]


Q8. For a dataset containing the following features: [height, weight, age, gender, blood pressure], perform Feature Extraction using PCA. How many principal components would you choose to retain, and why?


For the dataset with features: [height, weight, age, gender, blood pressure], PCA can be used to extract a smaller number of principal components.

The number of components to retain is typically based on the amount of variance explained. For example, choosing the smallest number of components that explain at least 95% of the total variance is a common strategy.

If 3 components explain 95% of the variance, those 3 are retained to reduce complexity while preserving information.
